server:
  port: ${PORT:0}

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Lookass/sphere-config-repo.git
          #cloneOnStart: true

management:
  endpoints:
    web:
      exposure:
        include: "*"  #<2>
  endpoint:
    health:
      show-details: ALWAYS